### ISSUE TITLE
How to plot figures like Fig. 2 for a given dataset

### ISSUE THREAD

**Issue by ShenZheng2000** [onpix/LCDPNet#1]
Hello, authors! I want to know how you obtain the Input luminance and the groundtruth/output luminance for Fig. 2. Is the luminance calculated from the pixel values of the images? What is the formula?
Thanks!

**Comment by onpix** [comment]
Hi! Thanks for your attention. Yeah, Fig. 2 is plotted using input-GT pixel values pairs in those datasets and pixels in the same image are marked in the same color.

**Comment by creeper121386** [comment]
Hi! Thanks for your attention. Yeah, Fig. 2 is plotted using input-GT pixel values pairs in those datasets and pixels in the same image are marked in the same color.
