### ISSUE TITLE
Excuse me, is there an easy way to use the pretrained model?

### ISSUE THREAD

**Issue by Mz1z** [onpix/LCDPNet#10]
I'am sorry for this issue, but I cannot run this project correctly.
I just want to test the effect of your trainning model but it is hard to run this code.
Is there an easy way to use the pretrained model? Just input an image and output an image.
Thank you.

**Comment by home56200** [comment]
I have the same question. Could you please explain clearly how to test your model, and what the input and output settings are?

**Comment by onpix** [comment]
Please refer to the Running section in the README.md file. It outlines the necessary steps to run the code. In short, you need to prepare your data and the pretrained model

- Update the `src/config/ds/test.yaml` file with the path to your test data. If you don't have ground truth (GT) images, set the GT value to false in the yaml file. Additionally, you can use command line arguments to specify any config field, like this: `python test.py test_ds.input.0=your/data/path/*.jpg`. In this way, you can indicate the input image (or images) in runtime.
- Execute `python src/test.py checkpoint_path=<file_path>` to indicate the path to your model.

Please refer to `facebook-hydra` doc if you have questions about the config.

**Comment by Leask** [comment]
Hi, I am sorry, I am so confused that the test.py is for "test the training"? Or "test the image enhancing"? And how can we use this project to enhance images? Please get back to me. Thanks!
