### ISSUE TITLE
Test.py execution problem

### ISSUE THREAD

**Issue by home56200** [onpix/LCDPNet#11]
![image](https://user-images.githubusercontent.com/48357577/230881899-2dce41e8-52ad-4ef6-acd4-aebdbfc25bca.png)
![image](https://user-images.githubusercontent.com/48357577/230881933-011ed655-a22a-4333-8ec8-974fbc4c0bad.png)

"I am testing the model you provided and have also made modifications to the test.yaml file. The test datasets are also the images you provided. How can I solve this error? Thank you."

The last line is the path of my model

**Comment by onpix** [comment]
So weird... I have not seen this error in my experiments. As it is raised in the pytorch distributed module, you may try turning off the ddp training. I also found a similar error [here](https://stackoverflow.com/questions/75875014/tcpstore-has-the-unmatched-in-format-string) but no one knows how to resolve it.

**Comment by home56200** [comment]
This is probably a PyTorch version issue, so creating a new environment has solved this problem, Thank you.
