### ISSUE TITLE
May I know what is the average time for validating one image?

### ISSUE THREAD

**Issue by home56200** [onpix/LCDPNet#12]
It was found from test.py that the model you provided takes more than 2 seconds on average to process a single image.
I tested input images with sizes of 512x512 or larger, up to 1280x1280.

![image](https://user-images.githubusercontent.com/48357577/231705164-e3e96f92-2e6d-4d2a-8c31-1154ab8d2a4a.png)

How long does it take for you to test one image?
Can you provide the code to convert the model to ONNX or TRT?

**Comment by onpix** [comment]
It depends on the GPU you use. In my experiments, it takes ~1s to process a 1080p image. For deployment,  please refer to [pytorch doc](https://pytorch.org/docs/stable/onnx.html?highlight=onnx#module-torch.onnx) or [pytorch-lightning doc](https://lightning.ai/docs/pytorch/latest/deploy/production_advanced.html).
