### ISSUE TITLE
运行test.py时报错使用您提供的预训练模型

### ISSUE THREAD

**Issue by blue-nothing** [onpix/LCDPNet#13]
![image](https://user-images.githubusercontent.com/60543667/235306815-ea9273ba-4763-4b7e-8645-40c1512b8bd1.png)
使用readme中的步骤运行，但是在member5或者6时总会报图片中的错误

**Comment by onpix** [comment]
看起来似乎是多卡训练导致的问题？由于条件限制，我们的实验都是用单gpu跑的，没有测试多卡运行。可以尝试改成单卡运行，看看是否还有问题。
