### ISSUE TITLE
Test.py Error

### ISSUE THREAD

**Issue by vietpho** [onpix/LCDPNet#14]
Hello, and thank you for your incredible work.

I attempted to test your model with my own datasets, and I configured the input path and checkpoint path accordingly. However, when I attempt to run test.py, I encounter the following error:

Traceback (most recent call last):
File "C:\work\enhancement\LCDPNet-main\src\test.py", line 31, in main
trainer = Trainer(
File "C:\Users\hyun\anaconda3\envs\torch38\lib\site-packages\pytorch_lightning\utilities\argparse.py", line 69, in insert_env_defaults
return fn(self, **kwargs)
TypeError: init() got an unexpected keyword argument 'gpus'

I have examined the Trainer class, and I cannot find the 'gpus' argument either. Could you assist me in resolving this issue?

Thank you.

**Comment by onpix** [comment]
I guess you used a newer pytorch-lightning version, which removes the `gpus` argument for `Trainer`. Installing `pytorch-lightning==1.7.6` may solve this problem.

**Comment by vietpho** [comment]
Thank you so much!

**Comment by thisisqiaoqiao** [comment]
Can you give me some guidance on how your code works when reproduced?
