### ISSUE TITLE
How to draw the input-ground truth luminance mapping curve?

### ISSUE THREAD

**Issue by kravrolens** [onpix/LCDPNet#16]
Hi, onpix. Thanks for sharing the excellent work!

The pictures in your paper are so beautiful and amazing! I would like to ask how to draw the input-ground truth luminance mapping curve like this? THANKS!

![1689943643185](https://github.com/onpix/LCDPNet/assets/57486569/19c5a9cc-7194-4ebf-abec-974e149e884b)

**Comment by onpix** [comment]
Thanks for your attention! these figures are produced using [matplotlib.pyplot.scatter](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html), by sampling N pixels for each input-GT pair, you can draw the mapping between each image pair as a colored scatter plot.

**Comment by kravrolens** [comment]
Thanks for your guidance, I've got it!
