### ISSUE TITLE
test problem

### ISSUE THREAD

**Issue by xiaomengyyy** [onpix/LCDPNet#18]
Hello author, why are the values of ssim and psnr 0 when testing with the training model 《trained_on_ours.ckpt》 you provided?
```
Test step: 218, Manual PSNR: 0.0, Manual SSIM: 0.0
[ TIMER ] Total time usage: 416.22171092033386

```

**Comment by onpix** [comment]
This can be caused by various reasons, such as the empty test dataset. Could you please provide more information?

**Comment by xiaomengyyy** [comment]
The test dataset is using the one you provided, which contains 218 images.
`libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Testing DataLoader 0:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 207/218 [06:52<00:21,  1.99s/it]libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Testing DataLoader 0: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 218/218 [07:13<00:00,  1.99s/it]
Test step: 218, Manual PSNR: 0.0, Manual SSIM: 0.0
[ TIMER ] Total time usage: 434.8139684200287
[ PATH ] The results are in :
/home/LCDPNet/pretrained_models/test_result/lcdpnet_pretrained_models_trained_on_ours.ckpt@lcdp_data.test
`

**Comment by onpix** [comment]
It looks weird. Do you have the correct conda env? If so, you may check if the output images are as expected. I am not sure what caused the problem, but it looks like a bug in metrices calculation.

**Comment by thisisqiaoqiao** [comment]
请问您解决这个问题了嘛？

**Comment by anayse** [comment]
I encountered the same issue during reproduction. After looking at the code, I found that the module for calculating PSNR and SSIM in the test_step of SingleNetBaseModel was commented out for some reason. Uncommenting it allows the values to be calculated.
