### ISSUE TITLE
test

### ISSUE THREAD

**Issue by zhaoyc823** [onpix/LCDPNet#20]
![0c41fd88f424818ab6722cf55c1602d](https://github.com/onpix/LCDPNet/assets/105473215/7c2b3112-de03-4139-961f-7fcce636792c)
How to solve this problem？

**Comment by zhaoyc823** [comment]
已解决

**Comment by thisisqiaoqiao** [comment]
请问您重新训练代码能跑通嘛

**Comment by zhaoyc823** [comment]
> 请问您重新训练代码能跑通嘛

我是仅跑的测试，测试代码是可以跑通的

**Comment by thisisqiaoqiao** [comment]
您测试代码的结果psrn为零嘛，我遇到了这个问题，所有指标为0。

**Comment by thisisqiaoqiao** [comment]
您测试代码的结果psrn为零嘛，我遇到了这个问题，所有指标为0。

**Comment by zhaoyc823** [comment]
好像是把gt中的图像设置为和input一致就可以解决了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月15日 22:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [onpix/LCDPNet] test (Issue #20) |

您测试代码的结果psrn为零嘛，我遇到了这个问题，所有指标为0。

**Comment by thisisqiaoqiao** [comment]
Thanks for your reply, can you give me some more coding tips?
