### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by thisisqiaoqiao** [onpix/LCDPNet#21]
RuntimeError: CUDA out of memory. Tried to allocate 856.00 MiB (GPU 0; 8.00 GiB total capacity; 2.96 GiB already allocated; 2.60 GiB free; 3.13 GiB reserved in total by PyTorch)
Although there is available VRAM, the system consistently displays "out of memory" error while running on Windows.

**Comment by onpix** [comment]
Please try reducing the batch size or image resolution, or add the code to empty the cache periodically.

**Comment by thisisqiaoqiao** [comment]
Thank you for your prompt reply. I adjusted the batchsize to 1 and still got the error. Can you give any more tips on changing the resolution?
![image](https://github.com/onpix/LCDPNet/assets/127526922/fae5ad76-1ff4-41f8-9bc8-c4ba4a33add6)

**Comment by onpix** [comment]
Looks like an env error rather than OOM, as it was raised upon import. Please make sure your env has no problem.

**Comment by thisisqiaoqiao** [comment]
I installed torch first: pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
Then proceed to install the libraries in the requirements.txt file. Not sure what's wrong with the environment.

**Comment by thisisqiaoqiao** [comment]
I seem to have found the cause of the problem, because I am running under windows and can train by changing dataloader_num_worker: 5 in the configuration file to 0. But there are always warnings appearing.
![image](https://github.com/onpix/LCDPNet/assets/127526922/ec9ccedd-1c2c-4764-b41c-3c8b38780633)

**Comment by onpix** [comment]
This is okay, it will not affect training.
