### ISSUE TITLE
About preparing LCDP dataset 

### ISSUE THREAD

**Issue by kravrolens** [onpix/LCDPNet#24]
Hi, Dr. Wang,

I am a PhD Candidates, mainly researching exposure correction tasks. The work you published in ECCV2022 titled "Local Color Distributions Prior for Image Enhancement" is very meaningful and inspiring.

 I want to ask your pipeline code for constructing LCDP dataset, such as ISP and linear transformation function. THANKS!

**Comment by onpix** [comment]
There is no code - the dataset is built using adobe light room. Please refer to the paper for details.
