### ISSUE TITLE
TypeError: cannot pickle 'cv2.TonemapReinhard' object

### ISSUE THREAD

**Issue by mvpzhangqiu** [onpix/LCDPNet#3]
你好！我想用自己的图片测试一下pretrain模型的效果，
在src/config/ds/test.yaml配置了图片路径
然后运行 python src/test.py checkpoint_path=trained_on_ours.ckptpython src/test.py checkpoint_path=trained_on_ours.ckpt

报了这个错误解决不了，想请教一下：
![屏幕截图 2022-10-18 104314](https://user-images.githubusercontent.com/14309504/196323366-f6a9a69d-983f-42e5-a354-4efd12f92737.png)

**Comment by onpix** [comment]
你好！抱歉没有及时回复。我并未遇到过该bug，故猜测可能是环境问题导致。你可以检查一下env中的python包版本和requirements.py中的是否相同。

**Comment by liuyingbin123** [comment]
> 你好！抱歉没有及时回复。我并未遇到过该bug，故猜测可能是环境问题导致。你可以检查一下env中的python包版本和requirements.py中的是否相同。

我觉得老哥应该补充一下python版本、python包的版本
