### ISSUE TITLE
Enhanced images with light sources have artifact 

### ISSUE THREAD

**Issue by beyzacevik** [onpix/LCDPNet#4]
Hello, 

Thank you for your contribution. I am conducting an experimental research on image enhancement. I've inferred results for a small dataset. I realized that the light source on the one of the results have a 'saturation artifact'. Do you know what causes this artifact and ow to eliminate it? May be clipping the output works. What do you think? 

Output image:
<img width="317" alt="Screen Shot 2022-12-16 at 16 22 02" src="https://user-images.githubusercontent.com/44713695/208130420-14c31c9b-f633-44be-a22f-ece4da168b5b.png">

Original Image:
<img width="557" alt="Screen Shot 2022-12-16 at 16 22 47" src="https://user-images.githubusercontent.com/44713695/208130608-cf897ed1-7ba8-4aa8-9bfa-3c49e6b60f16.png">

**Comment by onpix** [comment]
Hello! When a region is fully saturated (such as the light source in your example or the failure case in our paper), our model may produce unexpected output when suppressing overexposure. Because LCDPNet is essentially adjusting the exposure and color of the original pixels (by illumination map) rather than doing the inpainting.

**Comment by onpix** [comment]
A possible solution is to extend the training dataset. For the purpose of generalization, we built our current dataset based on Adobe5k and RAISE to cover diverse scenes, but maybe there are not enough images with the light source in our dataset. So extending more input-GT pairs with the light source may help.

**Comment by thisisqiaoqiao** [comment]
Can you give me some guidance on how your code works when reproduced?
