### ISSUE TITLE
Test-GT

### ISSUE THREAD

**Issue by 1359347500cwc** [onpix/LCDPNet#7]
I am very interested in your work, how can I get the GT of my test set when I test on my own dataset.
![image](https://user-images.githubusercontent.com/57097883/220357032-48eb8690-bca9-4f70-9183-66ec8d298b15.png)

**Comment by onpix** [comment]
If you want to compute metrics using GT, you need to prepare it. If GT images are not available (i.e., you can not obtain the paired well-exposed images), I suggest you set the GT path to `None` to predict the enhanced images without computing metrics.

**Comment by thisisqiaoqiao** [comment]
Can you give me some guidance on how your code works when reproduced?

**Comment by 1359347500cwc** [comment]
> Can you give me some guidance on how your code works when reproduced?

Just follow the readme.md below.
