### ISSUE TITLE
Pink pixels

### ISSUE THREAD

**Issue by calebhemara** [onpix/LCDPNet#8]
Hey! Great repo. Any idea why i'm getting pink pixels? Is this something you've seen? I have made decent modifications to simplify the inference for my project, but I can't see what I've done that could result in the pink artefacts. Thanks!

![IMG_8687-out](https://user-images.githubusercontent.com/79838938/222069457-00bdb3a1-e03c-49fd-b811-37b857acb9b7.jpg)
![IMG_8687](https://user-images.githubusercontent.com/79838938/222069468-ddad9f14-cd09-4967-bbea-b2be9e9a3d48.jpg)

**Comment by onpix** [comment]
Thanks for your feedback! Could you provide more details? e.g., Do you use our pretrained model or retrained on your dataset? And what does the input image looks like?

**Comment by calebhemara** [comment]
Thanks for your response!

I am using your pre-trained model to solve this before I train on my own data. The above is the input and output respectively, from inference. See bottom left table on top image to see pink artefacts.

I've downloaded your dataset to cross-check format of training data. Are your dataset .pngs exported from Lightroom? If so, perhaps the error is because they're 16bit, and I'm doing inference on 8bit images? 

Thanks!

**Comment by onpix** [comment]
The training images were exported from Lightroom with an 8-bit depth. I think the artifact is a result of this sample being out-of-distribution. ie, the input image doesn't have obvious both over or underexposures, and the model hasn't seen similar samples during training. To address this issue, it may be beneficial to train the model on your own dataset.
